security:
    # ...

    providers:
        users_in_memory: { memory: null }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # provider that you set earlier inside providers
            # provider: users_in_memory
            #     entity:
            #         class: App\Entity\User
            #             property: 

            form_login: 
                login_path: app_login
                check_path: app_login
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true